services:
  # 1. Serviço do Banco de Dados PostgreSQL
  - type: psql
    name: imobplat-db
    plan: free
    region: oregon # Garante que todos os serviços fiquem na mesma região

  # 2. Serviço do Back-end (NestJS)
  - type: web
    name: plataforma-imobiliaria
    runtime: node
    plan: free
    region: oregon
    rootDir: back_end
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: imobplat-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # O Render irá gerar um valor aleatório e seguro
      - key: FRONTEND_URL
        fromService:
          type: web
          name: imobplat-frontend
          property: url
      - key: NODE_ENV
        value: production

  # 3. Serviço do Front-end (Next.js)
  - type: web
    name: imobplat-frontend
    runtime: node
    plan: free
    region: oregon
    rootDir: front_end
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: plataforma-imobiliaria
          property: url