# Arquivo: render.yaml

databases:
  - name: imobplat-db
    region: oregon
    plan: free

services:
  # Serviço do Back-end (NestJS)
  - type: web
    name: plataforma-imobiliaria
    runtime: node
    plan: free
    region: oregon
    rootDir: back_end
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: imobplat-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      # CORREÇÃO: Definimos a URL do front-end explicitamente
      - key: FRONTEND_URL
        value: https://imobplat-frontend.onrender.com

  # Serviço do Front-end (Next.js)
  - type: web
    name: imobplat-frontend
    runtime: node
    plan: free
    region: oregon
    rootDir: front_end
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      # CORREÇÃO: Definimos a URL do back-end explicitamente
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://plataforma-imobiliaria.onrender.com