# Arquivo: render.yaml

databases:
  # 1. O banco de dados é definido aqui, na sua própria seção
  - name: imobplat-db
    region: oregon
    plan: free

services:
  # 2. Serviço do Back-end (NestJS)
  - type: web
    name: plataforma-imobiliaria
    runtime: node
    plan: free
    region: oregon
    rootDir: back_end
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: imobplat-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: imobplat-frontend
          property: url
      - key: NODE_ENV
        value: production

  # 3. Serviço do Front-end (Next.js)
  - type: web
    name: imobplat-frontend
    runtime: node
    plan: free
    region: oregon
    rootDir: front_end
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: plataforma-imobiliaria
          property: url